/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPluginDotjsonRouteImport } from './routes/api/plugin[.]json'
import { Route as ApiPluginApplyRouteImport } from './routes/api/plugin/apply'
import { Route as ApiPluginMcpRouteImport } from './routes/api/plugin/mcp'
import { Route as ApiPluginOpenapiDotjsonRouteImport } from './routes/api/plugin/openapi[.]json'
import { Route as ApiPluginStreamRouteImport } from './routes/api/plugin/stream'
import { Route as ApiPluginSwarmRouteImport } from './routes/api/plugin/swarm'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPluginDotjsonRoute = ApiPluginDotjsonRouteImport.update({
  id: '/api/plugin.json',
  path: '/api/plugin.json',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPluginApplyRoute = ApiPluginApplyRouteImport.update({
  id: '/api/plugin/apply',
  path: '/api/plugin/apply',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPluginMcpRoute = ApiPluginMcpRouteImport.update({
  id: '/api/plugin/mcp',
  path: '/api/plugin/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPluginOpenapiDotjsonRoute = ApiPluginOpenapiDotjsonRouteImport.update({
  id: '/api/plugin/openapi.json',
  path: '/api/plugin/openapi.json',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPluginStreamRoute = ApiPluginStreamRouteImport.update({
  id: '/api/plugin/stream',
  path: '/api/plugin/stream',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPluginSwarmRoute = ApiPluginSwarmRouteImport.update({
  id: '/api/plugin/swarm',
  path: '/api/plugin/swarm',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/plugin.json': typeof ApiPluginDotjsonRoute
  '/api/plugin/apply': typeof ApiPluginApplyRoute
  '/api/plugin/mcp': typeof ApiPluginMcpRoute
  '/api/plugin/openapi.json': typeof ApiPluginOpenapiDotjsonRoute
  '/api/plugin/stream': typeof ApiPluginStreamRoute
  '/api/plugin/swarm': typeof ApiPluginSwarmRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/plugin.json': typeof ApiPluginDotjsonRoute
  '/api/plugin/apply': typeof ApiPluginApplyRoute
  '/api/plugin/mcp': typeof ApiPluginMcpRoute
  '/api/plugin/openapi.json': typeof ApiPluginOpenapiDotjsonRoute
  '/api/plugin/stream': typeof ApiPluginStreamRoute
  '/api/plugin/swarm': typeof ApiPluginSwarmRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/plugin.json': typeof ApiPluginDotjsonRoute
  '/api/plugin/apply': typeof ApiPluginApplyRoute
  '/api/plugin/mcp': typeof ApiPluginMcpRoute
  '/api/plugin/openapi.json': typeof ApiPluginOpenapiDotjsonRoute
  '/api/plugin/stream': typeof ApiPluginStreamRoute
  '/api/plugin/swarm': typeof ApiPluginSwarmRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/plugin.json'
    | '/api/plugin/apply'
    | '/api/plugin/mcp'
    | '/api/plugin/openapi.json'
    | '/api/plugin/stream'
    | '/api/plugin/swarm'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/plugin.json'
    | '/api/plugin/apply'
    | '/api/plugin/mcp'
    | '/api/plugin/openapi.json'
    | '/api/plugin/stream'
    | '/api/plugin/swarm'
  id:
    | '__root__'
    | '/'
    | '/api/plugin.json'
    | '/api/plugin/apply'
    | '/api/plugin/mcp'
    | '/api/plugin/openapi.json'
    | '/api/plugin/stream'
    | '/api/plugin/swarm'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiPluginDotjsonRoute: typeof ApiPluginDotjsonRoute
  ApiPluginApplyRoute: typeof ApiPluginApplyRoute
  ApiPluginMcpRoute: typeof ApiPluginMcpRoute
  ApiPluginOpenapiDotjsonRoute: typeof ApiPluginOpenapiDotjsonRoute
  ApiPluginStreamRoute: typeof ApiPluginStreamRoute
  ApiPluginSwarmRoute: typeof ApiPluginSwarmRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/plugin.json': {
      id: '/api/plugin.json'
      path: '/api/plugin.json'
      fullPath: '/api/plugin.json'
      preLoaderRoute: typeof ApiPluginDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/plugin/apply': {
      id: '/api/plugin/apply'
      path: '/api/plugin/apply'
      fullPath: '/api/plugin/apply'
      preLoaderRoute: typeof ApiPluginApplyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/plugin/mcp': {
      id: '/api/plugin/mcp'
      path: '/api/plugin/mcp'
      fullPath: '/api/plugin/mcp'
      preLoaderRoute: typeof ApiPluginMcpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/plugin/openapi.json': {
      id: '/api/plugin/openapi.json'
      path: '/api/plugin/openapi.json'
      fullPath: '/api/plugin/openapi.json'
      preLoaderRoute: typeof ApiPluginOpenapiDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/plugin/stream': {
      id: '/api/plugin/stream'
      path: '/api/plugin/stream'
      fullPath: '/api/plugin/stream'
      preLoaderRoute: typeof ApiPluginStreamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/plugin/swarm': {
      id: '/api/plugin/swarm'
      path: '/api/plugin/swarm'
      fullPath: '/api/plugin/swarm'
      preLoaderRoute: typeof ApiPluginSwarmRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiPluginDotjsonRoute: ApiPluginDotjsonRoute,
  ApiPluginApplyRoute: ApiPluginApplyRoute,
  ApiPluginMcpRoute: ApiPluginMcpRoute,
  ApiPluginOpenapiDotjsonRoute: ApiPluginOpenapiDotjsonRoute,
  ApiPluginStreamRoute: ApiPluginStreamRoute,
  ApiPluginSwarmRoute: ApiPluginSwarmRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
